ci: create GHA for build
    - Also, remove the redundant GHA

Signed-off-by: Vicente Cheng <vicente.cheng@suse.com>

diff --git a/package/Dockerfile b/package/Dockerfile
--- a/package/Dockerfile
+++ b/package/Dockerfile
@@ -1,8 +1,19 @@
+# syntax=docker/dockerfile:1.7.0
+
 FROM registry.suse.com/bci/bci-base:15.5
 
 RUN zypper -n rm container-suseconnect && \
     zypper -n install util-linux-systemd lvm2 e2fsprogs nvme-cli device-mapper xfsprogs && \
     zypper -n clean -a && rm -rf /tmp/* /var/tmp/* /usr/share/doc/packages/*
 
-COPY bin/lvmplugin /usr/bin/
+ARG TARGETPLATFORM
+
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
+
+ENV ARCH=${TARGETPLATFORM#linux/}
+
+COPY bin/lvmplugin-${ARCH} /usr/bin/lvmplugin
 ENTRYPOINT ["lvmplugin"]
diff --git a/package/Dockerfile.provisioner b/package/Dockerfile.provisioner
--- a/package/Dockerfile.provisioner
+++ b/package/Dockerfile.provisioner
@@ -1,9 +1,19 @@
+# syntax=docker/dockerfile:1.7.0
+
 FROM registry.suse.com/bci/bci-base:15.5
 
 RUN zypper -n rm container-suseconnect && \
     zypper -n install lvm2 e2fsprogs smartmontools nvme-cli device-mapper && \ 
     zypper -n clean -a && rm -rf /tmp/* /var/tmp/* /usr/share/doc/packages/*
 
-COPY bin/csi-lvmplugin-provisioner /csi-lvmplugin-provisioner
+ARG TARGETPLATFORM
+
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
+
+ENV ARCH=${TARGETPLATFORM#linux/}
+COPY bin/csi-lvmplugin-provisioner-${ARCH} /usr/bin/csi-lvmplugin-provisioner
 USER root
 ENTRYPOINT ["csi-lvmplugin-provisioner"]
